import {
  TemplateConfig,
  SizeOption,
  FontStyleOption,
  ColorFilterOption,
  BadgeOption,
  CuratedBackdrop,
  KanjiStampPreset,
  TelemetryPreset,
  PostcardRenderState,
} from './postcardTypes';

export const TEMPLATES: TemplateConfig[] = [
  {
    id: 'neo_tokyo',
    label: 'Neo-Tokyo Midnight',
    subtitle: 'Cyberpunk Lo-Fi & Holographic HUD',
    emoji: '⚡',
    tag: 'Cyberpunk',
    primaryColor: '#00ffff',
    secondaryColor: '#ff007f',
    defaultFilter: 'cyber_neon',
    defaultFont: 'mono',
    defaultBadges: ['kanji_stamp', 'telemetry_hud', 'audio_waveform', 'sound_barcode'],
    desc: 'Electric neon cyan, glowing Japanese typography, futuristic telemetry & audio spectrum.',
  },
  {
    id: 'film_portra',
    label: '35mm Analog Portra',
    subtitle: 'Authentic Kodak Film Negative',
    emoji: '🎞️',
    tag: 'Vintage 35mm',
    primaryColor: '#f59e0b',
    secondaryColor: '#f97316',
    defaultFilter: 'vintage_sepia',
    defaultFont: 'playfair',
    defaultBadges: ['film_border', 'orange_date_stamp', 'color_palette'],
    desc: 'Kodak Portra 400 film borders with sprocket holes, warm analog grain, and 90s orange digital date.',
  },
  {
    id: 'golden_hour',
    label: 'Golden Hour Coast',
    subtitle: 'Wanderlust Highway Postcard',
    emoji: '🌅',
    tag: 'Warm Scenic',
    primaryColor: '#fbbf24',
    secondaryColor: '#f43f5e',
    defaultFilter: 'golden_hour',
    defaultFont: 'caveat',
    defaultBadges: ['postmark_stamp', 'orange_date_stamp', 'color_palette'],
    desc: 'Sunset gradient glow, scenic route airmail postmarks, and warm road trip aesthetics.',
  },
  {
    id: 'swiss_minimal',
    label: 'Swiss Gallery Art',
    subtitle: 'Modernist Museum Exhibition Print',
    emoji: '◼',
    tag: 'Minimal Editorial',
    primaryColor: '#ffffff',
    secondaryColor: '#a3a3a3',
    defaultFilter: 'noir_bw',
    defaultFont: 'syne',
    defaultBadges: ['color_palette', 'sound_barcode', 'audio_waveform'],
    desc: 'Architectural Swiss typography grid, extracted 4-color palette swatches, and clean museum catalog style.',
  },
  {
    id: 'synthwave_84',
    label: 'Outrun Synthwave \'84',
    subtitle: 'Neon Horizon Grid & Vinyl Sleeve',
    emoji: '🌴',
    tag: 'Retro 80s',
    primaryColor: '#ec4899',
    secondaryColor: '#8b5cf6',
    defaultFilter: 'vaporwave',
    defaultFont: 'outfit',
    defaultBadges: ['audio_waveform', 'telemetry_hud', 'sound_barcode'],
    desc: 'Perspective wireframe sun grid, chromatic scanlines, vinyl album border, and retro-futuristic vibes.',
  },
  {
    id: 'rainy_windshield',
    label: 'Midnight Rain Lo-Fi',
    subtitle: 'Cozy Highway & Glass Bokeh',
    emoji: '🌧️',
    tag: 'Moody Lo-Fi',
    primaryColor: '#38bdf8',
    secondaryColor: '#818cf8',
    defaultFilter: 'teal_orange',
    defaultFont: 'outfit',
    defaultBadges: ['kanji_stamp', 'audio_waveform'],
    desc: 'Atmospheric raindrop condensation, soft blurred bokeh lights, and frosted glass now-playing card.',
  },
  {
    id: 'cosmic_odyssey',
    label: 'Starlight Odyssey',
    subtitle: 'Deep Space Celestial Ambient',
    emoji: '🌌',
    tag: 'Deep Ambient',
    primaryColor: '#c084fc',
    secondaryColor: '#38bdf8',
    defaultFilter: 'natural',
    defaultFont: 'cinzel',
    defaultBadges: ['telemetry_hud', 'kanji_stamp', 'color_palette'],
    desc: 'Starfield constellation coordinates, deep celestial nebula glow, and pure cosmic minimalism.',
  },
];

export const SIZES: SizeOption[] = [
  {
    id: 'desktop_4k',
    label: 'Desktop Wallpaper',
    aspect: '16:9',
    w: 2560,
    h: 1440,
    hint: '2560 × 1440 (Ultra HD)',
    iconName: 'monitor',
  },
  {
    id: 'mobile_story',
    label: 'Mobile Lockscreen / Story',
    aspect: '9:16',
    w: 1080,
    h: 1920,
    hint: '1080 × 1920 (9:16 Phone)',
    iconName: 'smartphone',
  },
  {
    id: 'postcard',
    label: 'Classic Postcard',
    aspect: '16:10',
    w: 1600,
    h: 1000,
    hint: '1600 × 1000 (3:2 / 16:10)',
    iconName: 'mail',
  },
  {
    id: 'square_album',
    label: 'Square Album Art',
    aspect: '1:1',
    w: 1400,
    h: 1400,
    hint: '1400 × 1400 (Vinyl Cover)',
    iconName: 'square',
  },
  {
    id: 'ultrawide',
    label: 'Ultrawide Cinema Banner',
    aspect: '21:9',
    w: 2560,
    h: 1080,
    hint: '2560 × 1080 (Cinematic)',
    iconName: 'tv',
  },
];

export const FONT_STYLES: FontStyleOption[] = [
  {
    id: 'outfit',
    label: 'Outfit Clean',
    fontFamily: 'Outfit, sans-serif',
    previewSample: 'DRIVING VIBES',
    styleDesc: 'Modern geometric sans-serif with clean balance',
  },
  {
    id: 'cinzel',
    label: 'Cinzel Roman',
    fontFamily: 'Cinzel, serif',
    previewSample: 'CINEMATIC ODYSSEY',
    styleDesc: 'Classical Roman proportions & luxury cinematic titles',
  },
  {
    id: 'playfair',
    label: 'Playfair Display',
    fontFamily: '"Playfair Display", serif',
    previewSample: 'Analog Nostalgia',
    styleDesc: 'Editorial high-contrast vintage serif',
  },
  {
    id: 'mono',
    label: 'JetBrains Mono',
    fontFamily: '"JetBrains Mono", monospace',
    previewSample: 'SYS_LAT://35.6762_N',
    styleDesc: 'Technical developer & sci-fi telemetry monospaced',
  },
  {
    id: 'syne',
    label: 'Syne Bold',
    fontFamily: 'Syne, sans-serif',
    previewSample: 'SWISS GALLERY',
    styleDesc: 'Heavy avant-garde high-impact modernist style',
  },
  {
    id: 'caveat',
    label: 'Caveat Script',
    fontFamily: 'Caveat, cursive',
    previewSample: 'Wanderlust memories...',
    styleDesc: 'Handwritten road trip notes & spontaneous signatures',
  },
];

export const COLOR_FILTERS: ColorFilterOption[] = [
  {
    id: 'natural',
    label: 'Original / Natural',
    previewGradient: 'linear-gradient(135deg, #1e293b, #475569)',
  },
  {
    id: 'teal_orange',
    label: 'Teal & Orange',
    previewGradient: 'linear-gradient(135deg, #0284c7, #f97316)',
  },
  {
    id: 'cyber_neon',
    label: 'Cyberpunk Neon',
    previewGradient: 'linear-gradient(135deg, #06b6d4, #ec4899)',
  },
  {
    id: 'vintage_sepia',
    label: 'Vintage Portra \'84',
    previewGradient: 'linear-gradient(135deg, #78350f, #fbbf24)',
  },
  {
    id: 'golden_hour',
    label: 'Golden Hour Dusk',
    previewGradient: 'linear-gradient(135deg, #ea580c, #f43f5e)',
  },
  {
    id: 'noir_bw',
    label: 'High-Contrast Noir',
    previewGradient: 'linear-gradient(135deg, #09090b, #e4e4e7)',
  },
  {
    id: 'vaporwave',
    label: 'Vaporwave Pastel',
    previewGradient: 'linear-gradient(135deg, #a855f7, #38bdf8)',
  },
];

export const BADGE_OPTIONS: BadgeOption[] = [
  {
    id: 'kanji_stamp',
    label: 'Japanese Kanji Stamp',
    desc: 'Artistic Japanese Kanji calligraphy stamp',
    category: 'cyber',
    icon: '⛩️',
  },
  {
    id: 'telemetry_hud',
    label: 'Cyber HUD Telemetry',
    desc: 'GPS coordinates, speed, elevation & audio specs',
    category: 'cyber',
    icon: '🛰️',
  },
  {
    id: 'film_border',
    label: '35mm Film Sprocket Frame',
    desc: 'Authentic Kodak 35mm film negative perforations',
    category: 'retro',
    icon: '🎞️',
  },
  {
    id: 'postmark_stamp',
    label: 'Airmail Route Postmark',
    desc: 'Scenic highway & postal cancellation stamp',
    category: 'retro',
    icon: '📮',
  },
  {
    id: 'audio_waveform',
    label: 'Dynamic Sound Waveform',
    desc: 'Frequency spectrum visualizer bars',
    category: 'audio',
    icon: '📊',
  },
  {
    id: 'sound_barcode',
    label: 'Soundwave & Catalog Barcode',
    desc: 'Scannable aesthetic sound barcode with release ID',
    category: 'audio',
    icon: '🏷️',
  },
  {
    id: 'color_palette',
    label: 'Color Swatch Palette',
    desc: '4-color harmonic extraction chips with hex codes',
    category: 'minimal',
    icon: '🎨',
  },
  {
    id: 'orange_date_stamp',
    label: '90s Digital Date Stamp',
    desc: 'Vintage orange 7-segment digital camera timestamp',
    category: 'retro',
    icon: '📅',
  },
];

export const CURATED_BACKDROPS: CuratedBackdrop[] = [
  {
    id: 'app_art',
    title: 'Classic Driving Art',
    subtitle: 'Original Cinematic Illustration',
    category: 'Night',
    url: '/backgrounds/desktop-background.png',
    thumbnail: '/backgrounds/desktop-background.png',
  },
  {
    id: 'tokyo_rain_neon',
    title: 'Tokyo Neon Highway',
    subtitle: 'Wet asphalt reflections & illuminated skyscrapers',
    category: 'Night',
    url: '/backgrounds/tokyo-neon-desktop.jpg',
    thumbnail: '/backgrounds/tokyo-neon-mobile.jpg',
  },
  {
    id: 'pacific_coast_sunset',
    title: 'Pacific Coast Highway',
    subtitle: 'Golden hour sunset over the coastal ocean cliffs',
    category: 'Sunset',
    url: '/backgrounds/sunset-coast-desktop.jpg',
    thumbnail: '/backgrounds/sunset-coast-mobile.jpg',
  },
  {
    id: 'rainy_windshield_lights',
    title: 'Rainy Windshield Bokeh',
    subtitle: 'Nighttime traffic lights blurred through water droplets',
    category: 'Rain',
    url: '/backgrounds/rainy-drive-desktop.jpg',
    thumbnail: '/backgrounds/rainy-drive-mobile.jpg',
  },
  {
    id: 'mountain_pass_mist',
    title: 'Midnight Mountain Pass',
    subtitle: 'Foggy alpine serpentines under the moonlight',
    category: 'Nature',
    url: '/backgrounds/mountain-pass-desktop.jpg',
    thumbnail: '/backgrounds/mountain-pass-mobile.jpg',
  },
  {
    id: 'desert_highway_stars',
    title: '4AM Desert Starlight',
    subtitle: 'Empty open highway stretching beneath the Milky Way',
    category: 'Nature',
    url: '/backgrounds/desert-stars-desktop.jpg',
    thumbnail: '/backgrounds/desert-stars-mobile.jpg',
  },
  {
    id: 'synthwave_retro_grid',
    title: 'Synthwave Sunset Horizon',
    subtitle: 'Outrun wireframe sun and palm silhouette vector',
    category: 'Retro',
    url: '/backgrounds/synthwave-outrun-desktop.jpg',
    thumbnail: '/backgrounds/synthwave-outrun-mobile.jpg',
  },
];

export const QUOTES = [
  'Late night drives with nowhere to go.',
  'Chasing neon lights and quiet highways.',
  'Raindrops on the glass, peace in the mind.',
  'Lost in the rhythm of the open road.',
  'Moments when the music feels like home.',
  'Every mile feels like a memory.',
  'The city fades — only the music remains.',
  'Where the road ends, the vibe begins.',
  'Midnight reflections under ambient streetlights.',
  'Drifting between thoughts and soundscapes.',
  'Some roads exist just for healing.',
  'Turn the headlights down and let the soul drive.',
  'Speed of light, stillness of mind.',
  '4 AM thoughts in a moving sanctuary.',
  'Between dusk and dawn, we find ourselves.',
];

export const KANJI_STAMPS: KanjiStampPreset[] = [
  { id: 'midnight_drive', kanji: '深夜ドライブ', romaji: 'Shinya Doraibu', english: 'Midnight Drive' },
  { id: 'hyperspace',     kanji: '超時空',       romaji: 'Chōjikū',        english: 'Hyperspace' },
  { id: 'solitude',       kanji: '静寂',         romaji: 'Seijaku',        english: 'Serenity & Silence' },
  { id: 'journey',        kanji: '悠久の旅路',   romaji: 'Yūkyū no Tabiji', english: 'Endless Journey' },
  { id: 'city_pop',       kanji: '都市の灯',     romaji: 'Toshi no Hi',    english: 'City Lights' },
  { id: 'retro_vibe',     kanji: '追憶',         romaji: 'Tsuioku',        english: 'Nostalgia' },
];

export const TELEMETRY_PRESETS: TelemetryPreset[] = [
  {
    id: 'tokyo_express',
    title: 'Tokyo Shuto Expressway C1',
    coordinates: 'LAT 35.6762° N  ·  LON 139.6503° E',
    speed: '88 MPH / 141 KM/H',
    altitude: 'ELEV 42 M',
    heading: 'HDG 284° WNW',
    frequency: 'FM 80.0 TOKYO',
  },
  {
    id: 'pacific_coast',
    title: 'California State Route 1',
    coordinates: 'LAT 36.3615° N  ·  LON 121.8563° W',
    speed: '65 MPH / 104 KM/H',
    altitude: 'ELEV 185 M',
    heading: 'HDG 172° SSE',
    frequency: 'FM 94.7 PACIFIC',
  },
  {
    id: 'autobahn_night',
    title: 'German Autobahn A8',
    coordinates: 'LAT 48.1351° N  ·  LON 11.5820° E',
    speed: '124 MPH / 200 KM/H',
    altitude: 'ELEV 519 M',
    heading: 'HDG 090° E',
    frequency: 'CH 01 HI-RES 96kHz',
  },
  {
    id: 'cosmic_orbit',
    title: 'Deep Space Orbit Vector',
    coordinates: 'RA 18h 36m  ·  DEC +38° 47′',
    speed: '0.12 C (RELATIVISTIC)',
    altitude: 'ORBIT 4.2 AU',
    heading: 'VECTOR SECTOR 7',
    frequency: 'CARRIER 1420.405 MHz',
  },
];

export const DEFAULT_RENDER_STATE: PostcardRenderState = {
  template: 'neo_tokyo',
  size: 'postcard',
  backdropSource: 'curated',
  curatedBackdropId: 'app_art',
  customBackdropUrl: null,
  trackTitle: 'Midnight Highway Drift',
  artistName: 'Driving Vibes Ambient Radio',
  quote: QUOTES[0],
  customMessage: '',
  fontStyle: 'outfit',
  colorFilter: 'cyber_neon',
  activeBadges: {
    kanji_stamp: true,
    telemetry_hud: true,
    film_border: false,
    postmark_stamp: false,
    audio_waveform: true,
    sound_barcode: true,
    color_palette: true,
    orange_date_stamp: true,
  },
  selectedKanjiId: 'midnight_drive',
  selectedTelemetryId: 'tokyo_express',
  grainIntensity: 25,
  scanlinesIntensity: 20,
  vignetteIntensity: 40,
  blurIntensity: 0,
  contrastAmount: 110,
  saturationAmount: 115,
  lightLeakIntensity: 20,
};
