name = "live-counter"
main = "src/index.js"
compatibility_date = "2026-08-20"

[durable_objects]
bindings = [
  { name = "LIVE_COUNTER", class_name = "LiveCounter" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["LiveCounter"]

[observability]
enabled = true
